### ISSUE TITLE
Cache busting

### ISSUE THREAD

**Issue by lejoe** [ginetta/skeleton#85]
We want to avoid assets caching problems on our preview server.
Let's add cache busting to our dev/gulp tools so that our assets are always reloaded at each prod build.
Solution to come.

**Comment by lucalanca** [comment]
I was thinking since we use webpack + jade we can make use of these tools for that. Webpack already generates an hash for every chunk that can be used in the filename. Here's the steps I am thinking of: 


1. Use the hash in the output filename
```
output: { chunkFilename: "[chunkhash].bundle.js" }
``` 
2. Get hash data from stats when webpack finishes its dutty (I just wanted to use the word dutty :hankey: ) and pass it (somehow) to jade as a variable
```
plugins: [
  function() {
    this.plugin("done", function(stats) {
        // we get the info on the stats
  }
]
``` 

```
.pipe($.data(function(file) {
  return {
    helpers:      moduleHelpers,
    _      :      _,
    scriptsData: scriptsData
  };
}))
```
3. Use it on the layout
````
each script in scriptsData
    script(src='js/' + script + '.js'')
```

4. Make sure the `build:scripts` runs before `build:pages`

**Comment by lucalanca** [comment]
Done on #123
